minVersion: 0.1.0
github:
  owner: getsentry
  repo: script-runner
changelogPolicy: auto
preReleaseCommand: bash ./bin/bump-version.sh
releaseBranchPrefix: release
targets:
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
