mode: region
groups:
  kafka:
    python_module: examples.scripts.kafka
    iap_principals:
    - team-ops@sentry.io
    - team-streaming@sentry.io
  access_logs:
    python_module: examples.scripts.access_logs
    iap_principals: []
  example:
    python_module: examples.scripts.example
    iap_principals: []
region:
  name: s4s
  configs:
    kafka:
      clusters:
      - name: local
        brokers:
          - localhost:9092
    access_logs:
      host: localhost
      port: 9000
      database: clicktail
      table_name: access_log_local
