regions:
  - saas
  - de
  - s4s
python_scripts_module_name: examples.scripts
groups:
  kafka:
    auth:
      teams:
      - team-ops@sentry.io
      - team-streaming@sentry.io
  access_logs:
    auth:
      teams: []
  example: {}
region_configs:
  s4s:
    kafka:
      clusters:
      - name: local
        brokers:
          - localhost:9092
    access_logs:
      host: localhost
      port: 9000
      database: clicktail
      table_name: access_log_local
  saas:
    kafka:
      clusters:
      - name: local
        brokers:
          - localhost:9092
    access_logs:
      host: localhost
      port: 9000
      database: clicktail
      table_name: access_log_local
  de:
    kafka:
      clusters:
      - name: local
        brokers:
          - localhost:9092
    access_logs:
      host: localhost
      port: 9000
      database: clicktail
      table_name: access_log_local
