mode: main
groups:
  kafka:
    python_module: examples.scripts.kafka
    iap_principals:
    - team-ops@sentry.io
    - team-streaming@sentry.io
  access_logs:
    python_module: examples.scripts.access_logs
    iap_principals: []
  example:
    python_module: examples.scripts.example
    iap_principals: []
main:
  regions:
    - name: s4s
      url: localhost:5002

