mode: combined
groups:
  example:
    python_module: examples.scripts.example
authentication:
  method: no_auth
main:
  title: sentry script runner
  regions:
    - name: local
      url: localhost:5000
region:
  name: local
  configs: {}
audit_logs:
  console:
