[build-system]

requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.mypy]
strict = true

[project]
name = "script-runner"
version = "0.1.0"
description = "A web application for running Python scripts."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Lyn Nagara", email = "lyn@sentry.io" },
    { name = "Neo Huang", email = "neo.huang@sentry.io" },
]
requires-python = ">=3.12"
dependencies = [
    "flask>=2.0.0",
    "gunicorn>=20.1.0",
    "pyyaml>=6.0",
    "click>=8.1.0",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]

[project.scripts]
script-runner = "script_runner.cli:main"
